[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Developers/rpm86/EOSTEST/Lvl_EOSTest.Lvl_EOSTest
EditorStartupMap=/Game/Developers/rpm86/EOSTEST/Lvl_EOSTest.Lvl_EOSTest
GlobalDefaultGameMode="/Script/ZeroLock.ZeroLockGameMode"
GameInstanceClass=/Script/ZeroLock.Zero_BaseGameInstance

[/Script/Engine.RendererSettings]
r.ReflectionMethod=1
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.Lumen.TraceMeshSDFs=0
r.Shadow.Virtual.Enable=1
r.Mobile.EnableNoPrecomputedLightingCSMShader=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=true

r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8

r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6
-D3D11TargetedShaderFormats=PCD3D_SM5
+D3D11TargetedShaderFormats=PCD3D_SM5
Compiler=Default
AudioSampleRate=48000
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=1
AudioMaxChannels=0
AudioNumSourceWorkers=4
SpatializationPlugin=
SourceDataOverridePlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
CacheSizeKB=65536
MaxChunkSizeOverrideKB=0
bResampleForDevice=False
MaxSampleRate=48000.000000
HighSampleRate=32000.000000
MedSampleRate=24000.000000
LowSampleRate=12000.000000
MinSampleRate=8000.000000
CompressionQualityModifier=1.000000
AutoStreamingThreshold=0.000000
SoundCueCookQualityIndex=-1

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
-TargetedRHIs=SF_VULKAN_SM5
+TargetedRHIs=SF_VULKAN_SM6

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_ThirdPerson",NewGameName="/Script/ZeroLock")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_ThirdPerson",NewGameName="/Script/ZeroLock")
+ActiveClassRedirects=(OldClassName="TP_ThirdPersonGameMode",NewClassName="ZeroLockGameMode")
+ActiveClassRedirects=(OldClassName="TP_ThirdPersonCharacter",NewClassName="ZeroLockCharacter")
GameViewportClientClassName=/Script/CommonUI.CommonGameViewportClient

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=F4C1A9F446D0EE96A7B9A9B698073B8D
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


;This section enables the EOS OSS

[OnlineSubsystemEOS]
bEnabled=true
PlatformType=PC

;This section sets EOS as the platform

[OnlineSubsystem]
DefaultPlatformService=EOS

;This ensures the EOS NetDriver will be used

[/Script/Engine.GameEngine]
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineSubsystemEOS.NetDriverEOS",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")

;This section sets our EOS configuration to be used.
;The settings should match the config in the Developer Portal.
;As we are using Epic Account Services, bUseEas needs to be true

[/Script/OnlineSubsystemEOS.EOSSettings]
CacheDir=CacheDir
DefaultArtifactName=Zerolock_Server
RTCBackgroundMode=
TickBudgetInMilliseconds=0
bEnableOverlay=True
bEnableSocialOverlay=True
bEnableEditorOverlay=True
bPreferPersistentAuth=True
TitleStorageReadChunkLength=0
+Artifacts=(ArtifactName="Zerolock_Peer2Peer",ClientId="xyza78911ebuQW6o8unKMXpaacWMrTlS",ClientSecret="d6g2B8mhXgTFHhQG5cz4NIqg4hX0tyWT8vsAAHxUiR8",ProductId="e075ab7a9e514c5d90bc36142d8583f5",SandboxId="p-lnq3gflavbb7btyp42c2ej8397fhf6",DeploymentId="de9f7c607d0742e5b5dd2324e3f0469a",ClientEncryptionKey="1111111111111111111111111111111111111111111111111111111111111111")
+Artifacts=(ArtifactName="Zerolock_Server",ClientId="xyza78919CKGaxzB5aFjpM0hUnWVTq1Z",ClientSecret="c2lqGfVNVbJtQazmvc3OiXU/TrfDZ7mTfRPmWmzk0cI",ProductId="e075ab7a9e514c5d90bc36142d8583f5",SandboxId="p-lnq3gflavbb7btyp42c2ej8397fhf6",DeploymentId="de9f7c607d0742e5b5dd2324e3f0469a",ClientEncryptionKey="1111111111111111111111111111111111111111111111111111111111111111")
-AuthScopeFlags=BasicProfile
-AuthScopeFlags=FriendsList
-AuthScopeFlags=Presence
+AuthScopeFlags=BasicProfile
+AuthScopeFlags=FriendsList
+AuthScopeFlags=Presence
bUseEAS=True
bUseEOSConnect=True
bMirrorStatsToEOS=False
bMirrorAchievementsToEOS=False
bUseEOSSessions=False
bMirrorPresenceToEAS=False
bUseNewLoginFlow=False
SteamTokenType=Session
NintendoTokenType=NintendoServiceAccount

