;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Cooldown.Duration",DevComment="")
+GameplayTagList=(Tag="Event.WeaponHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Drifter.TeleporterMarked",DevComment="")
+GameplayTagList=(Tag="GC_ZeroLock.Drifter.TeleporterMark",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Abilities",DevComment="")
+GameplayTagList=(Tag="Zerolock.CoolDown.SevenStun",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Drifter.TeleporterHit",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Drifter.TeleporterMiss",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Guardian.BeamDamage",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Melee.Parry",DevComment="")
+GameplayTagList=(Tag="ZeroLock.MonkeyBoi.Stomp",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Seven.Stun",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Stun",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Weapon.Primary",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Weapon.Reloading",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.CoolDown.DrifterTeleport",DevComment="")

