;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.WeaponHit",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Abilities",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Melee.Parry",DevComment="")
+GameplayTagList=(Tag="ZeroLock.MonkeyBoi.Stomp",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Seven.Stun",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Stun",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Weapon.Primary",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Weapon.Reloading",DevComment="")

